[package]
name = "brain"
version = "0.1.0"
authors = ["Phillip Neal <philn1984@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
constants = { path = "../constants"}
rand = "0.8.3"
nannou = "0.16"


